version: '3'

services:
  db:
    container_name: mysql
    platform: linux/x86_64
    build:
      context: db
      dockerfile: ./Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
      LANG: 'ja_JP.UTF-8'
    tty: true
    restart: always
    user: root
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/data
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  app:
    container_name: api
    build: ./api
    volumes:
      - ./api:/code
    ports:
      - "80:80"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
