version: '3'

services:
  db:
    container_name: mysql
    build:
      context: ./db
    tty: true
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/init:/docker-entrypoint-initdb.d